Repository CarrotAuction/frontend, pull requests merged in 2023-11, with the labels that each got.

#2 Design/#1 Nav바 구현
  .eslintrc.json
  .husky/pre-commit
  package-lock.json
  package.json
  src/app/page.tsx
  src/common/Nav/index.module.scss
  src/common/Nav/index.tsx
  src/common/ui/ToggleNavIcon.tsx
  src/components/NavBarSlide/index.module.scss
  src/components/NavBarSlide/index.tsx
  src/constants/nav.ts
  src/hooks/useWindow.tsx
Labels: DESIGN

#7 Design/#6 경매 페이지 퍼블리싱
  .eslintrc.json
  next.config.js
  package-lock.json
  package.json
  src/app/(main)/index.module.scss
  src/app/(main)/page.tsx
  src/app/auction/index.module.scss
  src/app/auction/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/assets/auction/money.png
  src/assets/auction/profile.jpg
  src/assets/main/blueIntroduce3.png
  src/assets/main/blurIntroduce2.png
  src/assets/main/carrot.png
  src/assets/main/footer_carrot.png
  src/assets/main/introduce1.png
  src/assets/main/introduce2.png
  src/assets/main/introduce3.png
  src/assets/main/wallet.gif
  src/common/Footer/index.module.scss
  src/common/Footer/index.tsx
  src/common/Nav/index.module.scss
  src/common/Nav/index.tsx
  src/components/MainIntroduce/index.module.scss
  src/components/MainIntroduce/index.tsx
  src/components/MainIntroduce/useLazyLoading.tsx
  src/components/NavBarSlide/index.module.scss
  src/components/NavBarSlide/index.tsx
  src/components/auctionPage/AreaSelect/index.module.scss
  src/components/auctionPage/AreaSelect/index.tsx
  src/components/auctionPage/Banner/index.module.scss
  src/components/auctionPage/Banner/index.tsx
  src/components/auctionPage/Board/index.module.scss
  src/components/auctionPage/Board/index.tsx
  src/components/auctionPage/CategorySelect/index.module.scss
  src/components/auctionPage/CategorySelect/index.tsx
  src/components/auctionPage/CitySelect/index.module.scss
  src/components/auctionPage/CitySelect/index.tsx
  src/components/auctionPage/DataSearch/index.module.scss
  src/components/auctionPage/DataSearch/index.tsx
  src/components/auctionPage/FilterBox/index.module.scss
  src/components/auctionPage/FilterBox/index.tsx
  src/components/auctionPage/Options/index.module.scss
  src/components/auctionPage/Options/index.tsx
  src/components/auctionPage/Pagination/index.module.scss
  src/components/auctionPage/Pagination/index.tsx
  src/components/auctionPage/UserAuction/index.module.scss
  src/components/auctionPage/UserAuction/index.tsx
  src/components/auctionPage/UserAuctionData/index.module.scss
  src/components/auctionPage/UserAuctionData/index.tsx
  src/components/mainPage/Banner/index.module.scss
  src/components/mainPage/Banner/index.tsx
  src/constants/search.ts
  src/hooks/useInput.tsx
  src/hooks/useWindow.tsx
  src/styles/globalStyle.scss
  src/types/search.ts
Labels: DESIGN

#12 Design/#10 회원가입 페이지 퍼블리싱
  .eslintrc.json
  package-lock.json
  package.json
  src/app/login/index.module.scss
  src/app/login/page.tsx
  src/app/signUp/index.module.scss
  src/app/signUp/page.tsx
  src/components/auctionPage/AreaSelect/index.tsx
  src/components/signUpPage/Input/index.module.scss
  src/components/signUpPage/Input/index.tsx
  src/components/signUpPage/Select/AreaSelectBox/index.module.scss
  src/components/signUpPage/Select/AreaSelectBox/index.tsx
  src/components/signUpPage/Select/CitySelectBox/index.module.scss
  src/components/signUpPage/Select/CitySelectBox/index.tsx
  src/components/signUpPage/Select/Options/index.module.scss
  src/components/signUpPage/Select/Options/index.tsx
  src/constants/search.ts
  src/constants/signup.ts
  src/types/signup.ts
Labels: DESIGN

#16 feat: 로그인페이지 테스트코드 추가
  jest.config.ts
  jest.setup.ts
  package-lock.json
  package.json
  src/app/login/index.test.tsx
  src/app/login/page.tsx
Labels: FEAT

#18 Feat/#17 상수데이터 및 로직 변경
  src/components/auctionPage/AreaSelect/index.tsx
  src/components/auctionPage/CategorySelect/index.tsx
  src/components/auctionPage/CitySelect/index.tsx
  src/components/auctionPage/FilterBox/index.tsx
  src/components/auctionPage/Options/index.tsx
  src/constants/search.ts
  src/types/search.ts
Labels: FEAT

#22 refactor: 라우팅 설정안한 컴포넌트들 연결
  src/components/NavBarSlide/index.module.scss
  src/components/NavBarSlide/index.tsx
  src/components/auctionPage/Banner/index.tsx
  src/components/mainPage/Banner/index.tsx
Labels: REFACTOR

#25 feat: 회원가입 페이지 테스트코드 작성
  src/app/login/index.test.tsx
  src/app/signUp/index.test.tsx
  src/app/signUp/page.tsx
  src/components/signUpPage/Input/index.tsx
  src/types/signup.ts
Labels: FEAT

#27 feat: 회원가입 페이지 api 연동
  .eslintrc.json
  package-lock.json
  package.json
  src/apis/InitAxios/index.ts
  src/apis/Signup/index.ts
  src/app/signUp/page.tsx
  src/types/signup.ts
Labels: FEAT

#28 Feat/#26 로그인 api 연동
  .eslintrc.json
  package-lock.json
  package.json
  src/apis/Login/index.ts
  src/apis/Signup/index.ts
  src/app/login/index.test.tsx
  src/app/login/page.tsx
  src/common/Nav/index.tsx
  src/types/login.ts
  src/types/signup.ts
  src/utils/cookie.ts
Labels: FEAT

#39 feat: 경매글 생성 api 이미지 추가된 버전 연동
  next.config.js
  src/apis/Post/index.ts
  src/app/post/page.tsx
  src/assets/post/carrot.png
  src/components/auctionPage/BoardList/index.module.scss
  src/components/auctionPage/BoardList/index.tsx
  src/components/postPage/PostProductImage/index.tsx
  src/components/postPage/PostProductInfo/index.tsx
  src/hooks/usePreview.tsx
  src/types/post.ts
Labels: FEAT

#40 Chore/#38 storybook 초기설정
  .eslintrc.json
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  src/common/Nav/index.stories.tsx
  src/common/Nav/index.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
Labels: CHORE

#44 Chore/#41 ci 설정
  .github/workflows/ci.yml
  next.config.js
  package.json
  postcss.config.js
Labels: CHORE
